package me.mikex86.scicore.graph;

public enum OperationType {

    MATMUL, DIVIDE, PLUS, MINUS, REDUCE_SUM, EXP, TRANSPOSE, POW, MULTIPLY, RELU, SIGMOID, ARGMAX, CAST, COMPARE_ELEMENTS,
    PLUS_INPLACE, MINUS_INPLACE

}
