/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_mikex86_scicore_backend_impl_genericcpu_jni_MultiplyJNI */

#ifndef _Included_me_mikex86_scicore_backend_impl_genericcpu_jni_MultiplyJNI
#define _Included_me_mikex86_scicore_backend_impl_genericcpu_jni_MultiplyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_mikex86_scicore_backend_impl_genericcpu_jni_MultiplyJNI
 * Method:    nmultiply
 * Signature: (JIJJIJJJ)V
 */
JNIEXPORT void JNICALL Java_me_mikex86_scicore_backend_impl_genericcpu_jni_MultiplyJNI_nmultiply
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jint, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
